services:
  postgres:
    image: postgres:latest
    container_name: help_home
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: help_home 
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-database:/var/lib/postgresql/

volumes:
  postgre: